// examples/svelte-lottie-animation/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { Helios } from '@helios-project/core';
  import lottie from 'lottie-web';
  import animationData from './animation.json';

  let container;

  onMount(() => {
    // Initialize Helios
    const helios = new Helios({
      duration: 2,
      fps: 30,
    });

    // Initialize Lottie
    const anim = lottie.loadAnimation({
      container,
      renderer: 'svg',
      loop: false,
      autoplay: false,
      animationData,
    });

    // Subscribe to Helios updates
    const unsubscribe = helios.subscribe(({ currentFrame, fps }) => {
      const timeMs = (currentFrame / fps) * 1000;
      anim.goToAndStop(timeMs, false);
    });

    // Cleanup
    return () => {
      unsubscribe();
      anim.destroy();
    };
  });
</script>

<div bind:this={container} style="width: 100%; height: 100%;"></div>

// examples/solid-lottie-animation/src/App.jsx
import { createEffect, onMount, onCleanup } from 'solid-js';
import { createHeliosSignal } from './lib/createHeliosSignal';
import { Helios } from '@helios-project/core';
import lottie from 'lottie-web';
import animationData from './animation.json';

// Initialize Helios if not already present
if (!window.helios) {
  window.helios = new Helios({
    fps: 30,
    duration: 60, // frames
    width: 1920,
    height: 1080,
    autoStart: true,
  });
}

function App() {
  let containerRef;
  const frame = createHeliosSignal(window.helios);
  let animation = null;

  onMount(() => {
    if (!containerRef) return;

    animation = lottie.loadAnimation({
      container: containerRef,
      renderer: 'svg',
      loop: false,
      autoplay: false,
      animationData: animationData
    });

    onCleanup(() => {
      if (animation) {
        animation.destroy();
      }
    });
  });

  createEffect(() => {
    if (!animation) return;

    const state = frame();
    const { currentFrame } = state;
    const fps = window.helios.fps;

    const timeMs = (currentFrame / fps) * 1000;
    animation.goToAndStop(timeMs);
  });

  return (
    <div ref={containerRef} style={{ width: '100%', height: '100%' }} />
  );
}

export default App;
