// examples/react-transitions/src/components/Sequence.jsx
import React, { createContext, useContext } from 'react';

const FrameContext = createContext({ frame: 0, from: 0 });

export const Sequence = ({ from, duration, children, currentFrame, fps = 30 }) => {
  // Only render if within the time window
  if (currentFrame >= from && currentFrame < from + duration) {
    const startTime = from / fps;
    return (
      <FrameContext.Provider value={{ frame: currentFrame, from }}>
        <div style={{
          position: 'absolute', top: 0, left: 0, width: '100%', height: '100%',
          '--sequence-start': `${startTime}s`
        }}>
          {children}
        </div>
      </FrameContext.Provider>
    );
  }
  return null;
};

export const useSequence = () => useContext(FrameContext);

// examples/vue-transitions/src/components/Sequence.vue
<script setup>
import { computed, inject } from 'vue';

const props = defineProps({
  from: {
    type: Number,
    required: true
  },
  duration: {
    type: Number,
    required: true
  },
  fps: {
    type: Number,
    default: 30
  }
});

const currentFrame = inject('currentFrame');

const startTime = computed(() => props.from / props.fps);

const isActive = computed(() => {
  return currentFrame.value >= props.from && currentFrame.value < props.from + props.duration;
});
</script>

<template>
  <div v-if="isActive" :style="{ '--sequence-start': startTime + 's', position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }">
    <slot />
  </div>
</template>
