// examples/solid-transitions/src/components/Sequence.jsx
import { createMemo, Show } from 'solid-js';

export function Sequence(props) {
  // props: { frame: () => number, from: number, duration: number, helios: Helios, children: JSX.Element }

  const isActive = createMemo(() => {
    const f = props.frame();
    return f >= props.from && f < (props.from + props.duration);
  });

  const startTime = createMemo(() => props.from / props.helios.fps);

  return (
    <Show when={isActive()}>
      <div
        class="sequence-container"
        style={{
          "--sequence-start": `${startTime()}s`,
          position: 'absolute',
          top: 0,
          left: 0,
          width: '100%',
          height: '100%'
        }}
      >
        {props.children}
      </div>
    </Show>
  );
}

// examples/vue-transitions/src/components/Sequence.vue
<script setup>
import { computed, inject } from 'vue';

const props = defineProps({
  from: {
    type: Number,
    required: true
  },
  duration: {
    type: Number,
    required: true
  },
  fps: {
    type: Number,
    default: 30
  }
});

const currentFrame = inject('currentFrame');

const startTime = computed(() => props.from / props.fps);

const isActive = computed(() => {
  return currentFrame.value >= props.from && currentFrame.value < props.from + props.duration;
});
</script>

<template>
  <div v-if="isActive" :style="{ '--sequence-start': startTime + 's', position: 'absolute', top: 0, left: 0, width: '100%', height: '100%' }">
    <slot />
  </div>
</template>
