// examples/solid-transitions/src/App.jsx
import { createSignal, onMount, onCleanup } from 'solid-js';
import { Sequence } from './components/Sequence';

function App(props) {
  const [frame, setFrame] = createSignal(0);

  let unsubscribe;
  onMount(() => {
    unsubscribe = props.helios.subscribe((state) => {
      setFrame(state.currentFrame);
    });
  });

  onCleanup(() => {
    if (unsubscribe) unsubscribe();
  });

  return (
    <div class="container">
      <h1>Solid Transitions</h1>

      {/* Sequence 1: 0-60 frames */}
      <Sequence frame={frame} from={0} duration={60} helios={props.helios}>
        <div class="box fade-in" style={{ background: '#446b9e', top: '100px', left: '100px' }}>
          Solid
        </div>
      </Sequence>

      {/* Sequence 2: 60-120 frames */}
      <Sequence frame={frame} from={60} duration={60} helios={props.helios}>
        <div class="box slide-right" style={{ background: '#e94c4c', top: '250px', left: '100px' }}>
          Moves
        </div>
      </Sequence>
    </div>
  );
}

export default App;

// examples/vue-transitions/src/App.vue
<script setup>
import { ref, onMounted, onUnmounted, provide } from 'vue';
import { Helios } from '../../../packages/core/src/index.ts';
import Sequence from './components/Sequence.vue';

const currentFrame = ref(0);

// Initialize Helios with autoSyncAnimations: true
const helios = new Helios({
  fps: 30,
  duration: 4, // 120 frames
  autoSyncAnimations: true
});

helios.bindToDocumentTimeline();

// Expose to window for debugging/control
if (typeof window !== 'undefined') {
  window.helios = helios;
}

let unsubscribe;

onMounted(() => {
  unsubscribe = helios.subscribe((state) => {
    currentFrame.value = state.currentFrame;
  });
});

onUnmounted(() => {
  if (unsubscribe) unsubscribe();
});

provide('currentFrame', currentFrame);
</script>

<template>
  <div class="container">
    <h1>Vue Transitions</h1>

    <!-- Sequence 1: Starts at frame 0 -->
    <Sequence :from="0" :duration="60">
      <div class="box fade-in" style="background: #42b883; top: 100px; left: 100px; position: absolute;">
        Vue
      </div>
    </Sequence>

    <!-- Sequence 2: Starts at frame 60 (2s) -->
    <Sequence :from="60" :duration="60">
      <div class="box slide-right" style="background: #35495e; top: 250px; left: 100px; position: absolute;">
        Move
      </div>
    </Sequence>
  </div>
</template>

<style>
@import './style.css';
h1 {
  color: white;
  padding: 20px;
  margin: 0;
}
</style>
