// examples/react-canvas-animation/src/App.tsx
import React, { useEffect, useRef } from 'react';
import { Helios } from '@helios/core';

const App = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    // Handle resizing
    const resize = () => {
      canvas.width = window.innerWidth;
      canvas.height = window.innerHeight;
    };
    resize();
    window.addEventListener('resize', resize);

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const helios = new Helios({
      duration: 5,
      fps: 30
    });

    helios.bindToDocumentTimeline();

    const draw = (frame: number) => {
        const { width, height } = canvas;
        const totalFrames = 30 * 5;
        const progress = frame / totalFrames;

        ctx.fillStyle = '#1a1a1a';
        ctx.fillRect(0, 0, width, height);

        // Draw a rotating React logo-ish thing
        const cx = width / 2;
        const cy = height / 2;

        ctx.save();
        ctx.translate(cx, cy);
        ctx.rotate(progress * Math.PI * 2);

        ctx.strokeStyle = '#61dafb';
        ctx.lineWidth = 5;
        ctx.beginPath();
        ctx.ellipse(0, 0, 100, 40, 0, 0, Math.PI * 2);
        ctx.stroke();

        ctx.rotate(Math.PI / 3);
        ctx.beginPath();
        ctx.ellipse(0, 0, 100, 40, 0, 0, Math.PI * 2);
        ctx.stroke();

        ctx.rotate(Math.PI / 3);
        ctx.beginPath();
        ctx.ellipse(0, 0, 100, 40, 0, 0, Math.PI * 2);
        ctx.stroke();

        ctx.beginPath();
        ctx.arc(0, 0, 10, 0, Math.PI * 2);
        ctx.fillStyle = '#61dafb';
        ctx.fill();

        ctx.restore();
    };

    const unsubscribe = helios.subscribe((state) => {
        draw(state.currentFrame);
    });

    // Initial draw
    draw(0);

    return () => {
        unsubscribe();
        window.removeEventListener('resize', resize);
    };
  }, []);

  return <canvas ref={canvasRef} />;
};

export default App;

// examples/svelte-canvas-animation/src/App.svelte
<script>
  import { onMount, onDestroy } from 'svelte';
  import { Helios } from '../../../packages/core/src/index.ts';
  import { createHeliosStore } from './lib/store';

  let canvas;
  let ctx;
  const duration = 5;
  const fps = 30;

  // Initialize Helios
  const helios = new Helios({
    duration,
    fps
  });

  helios.bindToDocumentTimeline();

  if (typeof window !== 'undefined') {
    window.helios = helios;
  }

  const heliosStore = createHeliosStore(helios);

  // Reactive drawing
  $: if (ctx && $heliosStore) {
    draw($heliosStore.currentFrame);
  }

  function draw(currentFrame) {
      const time = currentFrame / fps * 1000; // in ms
      const progress = (time % (duration * 1000)) / (duration * 1000);

      const width = canvas.width;
      const height = canvas.height;

      // Clear
      ctx.fillStyle = '#111';
      ctx.fillRect(0, 0, width, height);

      const x = progress * width;
      const y = height / 2;
      const radius = 50;

      // Draw moving circle
      ctx.fillStyle = 'royalblue';
      ctx.beginPath();
      ctx.arc(x, y, radius, 0, Math.PI * 2);
      ctx.fill();

      // Draw rotating square
      const squareSize = 100;
      ctx.save();
      ctx.translate(width / 2, height / 2);
      ctx.rotate(progress * Math.PI * 2);
      ctx.fillStyle = 'tomato';
      ctx.fillRect(-squareSize / 2, -squareSize / 2, squareSize, squareSize);
      ctx.restore();
  }

  const resizeCanvas = () => {
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    if (ctx && $heliosStore) {
      draw($heliosStore.currentFrame);
    }
  };

  onMount(() => {
    ctx = canvas.getContext('2d');
    resizeCanvas();
    window.addEventListener('resize', resizeCanvas);
  });

  onDestroy(() => {
     if (typeof window !== 'undefined') {
        window.removeEventListener('resize', resizeCanvas);
     }
  });

</script>

<canvas bind:this={canvas} style="display: block; width: 100%; height: 100%;"></canvas>

<style>
  :global(body) {
    margin: 0;
    overflow: hidden;
    background-color: #111;
  }
</style>
