// examples/svelte-lottie-animation/src/App.svelte
<script>
  import { onMount } from 'svelte';
  import { Helios } from '@helios-project/core';
  import lottie from 'lottie-web';
  import animationData from './animation.json';

  let container;

  onMount(() => {
    // Initialize Helios
    const helios = new Helios({
      duration: 2,
      fps: 30,
    });

    // Initialize Lottie
    const anim = lottie.loadAnimation({
      container,
      renderer: 'svg',
      loop: false,
      autoplay: false,
      animationData,
    });

    // Subscribe to Helios updates
    const unsubscribe = helios.subscribe(({ currentFrame, fps }) => {
      const timeMs = (currentFrame / fps) * 1000;
      anim.goToAndStop(timeMs, false);
    });

    // Cleanup
    return () => {
      unsubscribe();
      anim.destroy();
    };
  });
</script>

<div bind:this={container} style="width: 100%; height: 100%;"></div>

// examples/vue-lottie-animation/src/App.vue
<script setup>
import { onMounted, onUnmounted, ref } from 'vue';
import { Helios } from '@helios-project/core';
import lottie from 'lottie-web';
import animationData from './animation.json';

const container = ref(null);
const helios = new Helios({ fps: 30, duration: 2 });
let anim = null;
let unsubscribe = null;

onMounted(() => {
  anim = lottie.loadAnimation({
    container: container.value,
    renderer: 'svg',
    loop: false,
    autoplay: false,
    animationData
  });

  unsubscribe = helios.subscribe(({ currentFrame, fps }) => {
    const timeMs = (currentFrame / fps) * 1000;
    anim.goToAndStop(timeMs, false);
  });
});

onUnmounted(() => {
  if (unsubscribe) unsubscribe();
  if (anim) anim.destroy();
});
</script>

<template>
  <div ref="container" class="lottie-container"></div>
</template>

<style>
.lottie-container {
  width: 100%;
  height: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}
</style>
