// examples/variable-font-animation/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './style.css';
import { Helios } from '@helios-project/core';

const helios = new Helios({
  fps: 30,
  duration: 4, // Match animation duration
  autoSyncAnimations: true
});

helios.bindToDocumentTimeline();
(window as any).helios = helios;

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// examples/solid-transitions/src/index.jsx
import { render } from 'solid-js/web';
import { Helios } from '@helios-project/core';
import App from './App';
import './style.css';

// Initialize Helios
const helios = new Helios({
  duration: 4, // 120 frames
  fps: 30,
  autoSyncAnimations: true // Crucial for this example
});

helios.bindToDocumentTimeline();

// Expose to window for debugging/control
if (typeof window !== 'undefined') {
  window.helios = helios;
}

render(() => <App helios={helios} />, document.getElementById('root'));
