// examples/solid-d3-animation/src/index.jsx
/* @refresh reload */
import { render } from 'solid-js/web';
import App from './App';
import { Helios } from '@helios-project/core';

// Initialize Helios
window.helios = new Helios({
  width: 1920,
  height: 1080,
  autoSyncAnimations: false, // We will manually drive D3
  fps: 60,
  duration: 60 // Default duration
});

// Bind to document timeline for simple playback control
window.helios.bindToDocumentTimeline();

render(() => <App />, document.getElementById('root'));

// examples/variable-font-animation/src/main.tsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './style.css';
import { Helios } from '@helios-project/core';

const helios = new Helios({
  fps: 30,
  duration: 4, // Match animation duration
  autoSyncAnimations: true
});

helios.bindToDocumentTimeline();
(window as any).helios = helios;

ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
