// examples/vue-dom-animation/src/App.vue
<script setup lang="ts">
import { Helios } from '@helios-project/core';
import { useVideoFrame } from './composables/useVideoFrame';

// Initialize Helios singleton
const duration = 5;
const fps = 30;
const helios = new Helios({ duration, fps });
helios.bindToDocumentTimeline();

// Expose to window for debugging/player control
if (typeof window !== 'undefined') {
    (window as any).helios = helios;
}

const frame = useVideoFrame(helios);
</script>

<template>
  <div class="container">
    <div
        class="box"
        :style="{
            opacity: Math.min(1, frame / 30),
            transform: `scale(${Math.min(1.5, 0.5 + frame / 150)}) rotate(${frame * 2}deg)`
        }"
    >
        Vue DOM
    </div>
    <div class="info">Frame: {{ frame.toFixed(2) }}</div>
  </div>
</template>

<style scoped>
.container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    height: 100%;
    color: white;
    font-family: sans-serif;
}
.box {
    width: 200px;
    height: 200px;
    background-color: #42b883;
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 2rem;
    font-weight: bold;
    border-radius: 20px;
    box-shadow: 0 0 20px rgba(66, 184, 131, 0.5);
    border: 4px solid #35495e;
}
.info {
    margin-top: 2rem;
    font-size: 1.5rem;
}
</style>

// examples/svelte-runes-animation/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { Helios } from '@helios-project/core';
  import { HeliosState } from './lib/helios.svelte.ts';

  // Initialize Helios
  const helios = new Helios({
    duration: 5,
    fps: 30,
    autoSyncAnimations: true
  });

  // Create reactive state wrapper
  const state = new HeliosState(helios);

  // Expose to window for player
  onMount(() => {
    if (typeof window !== 'undefined') {
      (window as any).helios = helios;
    }
  });

  // Derived state for animation logic
  // Progress 0..1
  let progress = $derived(state.currentFrame / (state.duration * state.fps));

  // Animation values
  let x = $derived(progress * 300);
  let rotation = $derived(progress * 360);
</script>

<div class="scene">
  <div
    class="box"
    style="transform: translate({x}px, 0) rotate({rotation}deg);"
  >
    {state.currentFrame}
  </div>
</div>

<style>
  :global(body) {
    margin: 0;
    overflow: hidden;
  }
  .scene {
    width: 100%;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #111;
    color: white;
  }
  .box {
    width: 100px;
    height: 100px;
    background: linear-gradient(45deg, #ff3e00, #ff8c00);
    border-radius: 12px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-family: sans-serif;
    font-weight: bold;
    font-size: 24px;
    will-change: transform;
  }
</style>
