// examples/variable-font-animation/src/main.jsx
import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './style.css';
import { Helios } from '../../../packages/core/src/index.ts';

const helios = new Helios({
  fps: 30,
  duration: 4, // Match animation duration
  autoSyncAnimations: true
});

helios.bindToDocumentTimeline();
window.helios = helios;

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);

// examples/solid-dom-animation/src/index.jsx
import { render } from 'solid-js/web';
import App from './App';
import { Helios } from '../../../packages/core/src/index.ts';

// Initialize Helios
const helios = new Helios({
  duration: 5,
  fps: 30,
  autoSyncAnimations: true
});
window.helios = helios;
helios.bindToDocumentTimeline();

render(() => <App />, document.getElementById('app'));
