// examples/react-animation-helpers/src/components/Series.jsx
import React, { Children, cloneElement, isValidElement } from 'react';

export const Series = ({ children }) => {
  let currentFrom = 0;

  return (
    <>
      {Children.map(children, (child) => {
        if (!isValidElement(child)) {
          return child;
        }

        const duration = child.props.durationInFrames || 0;
        const newProps = { from: currentFrom };
        currentFrom += duration;

        return cloneElement(child, newProps);
      })}
    </>
  );
};

// examples/vue-animation-helpers/src/components/Series.vue
<script>
import { cloneVNode } from 'vue';

function getChildren(slot) {
  const children = slot ? slot() : [];
  return children.flat();
}

export default {
  name: 'Series',
  setup(props, { slots }) {
    return () => {
      let currentFrom = 0;
      const children = getChildren(slots.default);

      return children.map(child => {
        // Robust check for props
        if (!child || typeof child !== 'object') return child;

        // Try to get durationInFrames from props.
        const duration = child.props?.durationInFrames || 0;

        const newFrom = currentFrom;
        currentFrom += Number(duration);

        return cloneVNode(child, { from: newFrom });
      });
    };
  }
}
</script>
