// examples/vue-animation-helpers/src/App.vue
<script setup>
import { ref, provide, onUnmounted, computed } from 'vue';
import { Helios, interpolate, spring } from '../../../packages/core/src/index.ts';
import Sequence from './components/Sequence.vue';
import Series from './components/Series.vue';

const helios = new Helios({ duration: 5, fps: 30 });
helios.bindToDocumentTimeline();

if (typeof window !== 'undefined') {
  window.helios = helios;
}

const frame = ref(0);

const unsubscribe = helios.subscribe((state) => {
  frame.value = state.currentFrame;
});

onUnmounted(() => {
  unsubscribe();
});

const x = computed(() => interpolate(frame.value, [0, 60], [0, 200], { extrapolateRight: 'clamp' }));
const scale = computed(() => spring({ frame: frame.value, fps: 30, from: 0, to: 1, config: { stiffness: 100 } }));

provide('videoFrame', frame);
</script>

<template>
  <div class="container">
    <h1>Vue Animation Helpers</h1>
    <div>Root Frame: {{ frame.toFixed(2) }}</div>

    <Series>
      <!-- Sequence 1: 0-30 frames -->
      <Sequence :durationInFrames="30">
        <div class="box red">Seq 1</div>
      </Sequence>

      <!-- Sequence 2: 30-60 frames -->
      <Sequence :durationInFrames="30">
        <div class="box blue">Seq 2</div>
      </Sequence>

      <!-- Sequence 3: Nested -->
      <Sequence :durationInFrames="60">
          <div>Wrapper (60-120)</div>
          <Sequence :from="0" :durationInFrames="30">
              <div class="box green">Nested 1</div>
          </Sequence>
          <Sequence :from="30" :durationInFrames="30">
              <div class="box yellow">Nested 2</div>
          </Sequence>
      </Sequence>
    </Series>

    <div :style="{
      position: 'absolute',
      top: '250px',
      left: '50px',
      transform: `translateX(${x}px) scale(${scale})`,
      width: '100px',
      height: '100px',
      background: 'hotpink',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: 'white',
      fontWeight: 'bold',
      border: '2px solid white'
    }">
      Helpers
    </div>
  </div>
</template>

<style>
body {
    margin: 0;
    background: #111;
    color: white;
    font-family: sans-serif;
}
.container {
    padding: 20px;
}
.box {
    width: 100px;
    height: 100px;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    margin: 10px;
    color: white;
}
.red { background: red; }
.blue { background: blue; }
.green { background: green; }
.yellow { background: yellow; color: black; }
</style>

// examples/svelte-animation-helpers/src/App.svelte
<script>
  import { setContext } from 'svelte';
  import { derived } from 'svelte/store';
  import { Helios, interpolate, spring } from '../../../packages/core/src/index.ts';
  import { createHeliosStore } from './lib/store';
  import { FRAME_CONTEXT_KEY } from './lib/context';
  import Sequence from './lib/Sequence.svelte';
  import Series from './lib/Series.svelte';

  const duration = 5;
  const fps = 30;

  // Initialize Helios
  const helios = new Helios({
    duration,
    fps
  });

  helios.bindToDocumentTimeline();

  if (typeof window !== 'undefined') {
    window.helios = helios;
  }

  const heliosStore = createHeliosStore(helios);
  const currentFrame = derived(heliosStore, $s => $s.currentFrame);

  setContext(FRAME_CONTEXT_KEY, currentFrame);

  $: x = interpolate($currentFrame, [0, 60], [0, 200], { extrapolateRight: 'clamp' });
  $: scale = spring({ frame: $currentFrame, fps, from: 0, to: 1, config: { stiffness: 100 } });
</script>

<div class="container">
    <h1 style:color="white">Svelte Animation Helpers</h1>

    <Series>
        <!-- Sequence 1: 0-30 frames -->
        <Sequence durationInFrames={30}>
            <div class="box" style:background="red">
                Seq 1
            </div>
        </Sequence>

        <!-- Sequence 2: 30-60 frames -->
        <Sequence durationInFrames={30}>
            <div class="box" style:background="blue">
                Seq 2
            </div>
        </Sequence>

        <!-- Sequence 3: Nested (Starts at 60) -->
        <Sequence durationInFrames={60}>
             <div style:color="white">Wrapper (60-120)</div>

             <!-- Inner Series -->
             <Series>
                 <Sequence durationInFrames={30}>
                     <div class="box" style:background="green">
                         Nested 1
                     </div>
                 </Sequence>
                 <Sequence durationInFrames={30}>
                     <div class="box" style:background="yellow" style:color="black">
                         Nested 2
                     </div>
                 </Sequence>
             </Series>
        </Sequence>
    </Series>

    <div style:position="absolute"
         style:top="250px"
         style:left="50px"
         style:transform="translateX({x}px) scale({scale})"
         style:width="100px"
         style:height="100px"
         style:background="hotpink"
         style:display="flex"
         style:align-items="center"
         style:justify-content="center"
         style:color="white"
         style:font-weight="bold"
         style:border="2px solid white">
        Helpers
    </div>
</div>

<style>
  :global(body) {
    margin: 0;
    overflow: hidden;
    background-color: #111;
    font-family: sans-serif;
  }
  .container {
    padding: 20px;
  }
  .box {
    width: 100px;
    height: 100px;
    color: white;
    display: flex;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    margin: 10px;
  }
</style>
